language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script: 
  - pytest -v --cov-report term-missing --cov=app
  
after_success:
  - coveralls

notifications:
  email: false